# General site settings.
base_url = "https://sigil.box"
title = "Sigil"
description = "An Ethereum L2"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false
build_search_index = false
generate_feeds = true
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[extra]
# Site header (shown on all pages)
header_name = "Sigil"
header_bio = "An Ethereum L2 for believers."
header_avatar = "img/LogoMark_CandlelightYellow.png"
header_avatar_light = "img/LogoMark_SigilRed.png"
header_links = [
  { name = "GitHub", icon = "github", url = "https://github.com/unattended-backpack" },
  { name = "Twitter", icon = "twitter", url = "https://twitter.com/Sigil_L2" },
  { name = "Email", icon = "email", url = "mailto:root@sigil.box" },
]

sections = [
  { name = "about", path = "/about", is_external = false },
  { name = "posts", path = "/posts", is_external = false },
]
blog_section_path = "/posts"
back_link_text = "Back"
force_theme = false
footer_copyright = "VPL-licensed; copyleft (ɔ) all rights reversed"
footer_credits = false
not_found_error_text = "404"
not_found_recover_text = "bring me home"
reaction = false 
reaction_align = "right"
reaction_endpoint = ""
